FROM eclipse-temurin:17.0.4.1_1-jre as build
WORKDIR extracted
ADD target/*.jar app.jar
RUN java -Djarmode=layertools -jar app.jar extract

FROM eclipse-temurin:17.0.4.1_1-jre
WORKDIR application
COPY --from=build extracted/dependencies/ ./
COPY --from=build extracted/spring-boot-loader/ ./
COPY --from=build extracted/snapshot-dependencies/ ./
COPY --from=build extracted/application/ ./
EXPOSE 8084
ENTRYPOINT [ "java", "org.springframework.boot.loader.JarLauncher" ]
